### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by forabi** [hollowverse-archive/hollowverse#123]
This is a tracking issue for v1.

## Flow
![hollowverse v1 flow](https://user-images.githubusercontent.com/1012761/27959282-7639111e-632f-11e7-938d-167bd2f8e3dc.png)

## Tasks
* [x] Write a `Dockerfile` to build the application
* [x] Switch our CI process to use the new docker image
* [x] Redirect one NP page to the new version
  * [x] Pick one NP (e.g. Katherine Webb)
  * [x] Manually enter NP data into Firebase, indexed by ID (`np_123456`)
  * [x] Choose a URL for NP that matches Wikipedia's page for that NP (`Katherine_Webb`)
  * [x] Create a map from old URL schema to new one, and add entry for this NP (`katherine-webb => Katherine_Webb`). This could be a simple JS object for now, stored on the redirection proxy (see below). It may be moved to Firebase later as we start redirecting more pages.
  * [x] Map the new URL to the respective NP ID as stored in Firebase (`Katherine_Webb => np_123456`). This new map should also be stored in Firebase.
  * [x] Write a redirection proxy as a node.js script: this proxy decides whether a request for a notable person should go to the new version or the old one by looking at the map. If the map contains the NP, it redirects to the new version, otherwise the request goes to the old version.
  * [x] Write a Firebase cloud function that does the following:
    1. takes the new NP URL (`Katherine_Webb`)
    2. fetches that NP ID from Firebase (`np_123456`) using the map created previously
    3. fetches the actual NP data stored at that ID
    4. Returns the data to the client

**Comment by wholesomedev** [comment]
I think once we deploy the new web app and start taking all traffic on it (even if all it does is proxying the traffic to the old website), we can call it v1 and close out this issue.

**Comment by wholesomedev** [comment]
This looks like it's done. Should we close it?

**Comment by forabi** [comment]
Yes. Closed.
